# Defined as pipeline variables
# variables:
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

jobs: 
- template: templates/cpu.yml
  parameters:
    AgentPool : 'Win-CPU-2019'
    DoEsrp: 'false'
